### PR TITLE
Ml classification

### PR DESCRIPTION
**Pull request by shark8me**
Support for Spark Machine learning libraries. Currently has support for classification alone. 

Documentation/demo as a gorilla-repl in a fork of the sparking-getting-started repo [in this link](http://viewer.gorilla-repl.org/view.html?source=github&user=eyeota&repo=sparkling-getting-started&path=ws/classification-guide.cljw?ref=classification-guide). 

The build on oraclejdk7 containers fail because of insufficient heap space, hence that container is removed from .travis.yml.

### CODE REVIEW

**Comment by chrisbetz** [comment]
That looks good to me, thanks a lot! I'll make a new version including your PR really soon.

**Comment by shark8me** [comment]
Hi,
Is there anything I can help with, to get a new version with this PR? 

thanks!

**Comment by chrisbetz** [comment]
Hi,

sorry, been extremly busy the last weeks on my new job. Now I'm ready to go and I'm actually taking a look into open PRs and Issues to get a new version soon. Thanks for asking.

I still see trouble on Travis Build and tests in Oracle JDK 8, need to look into this first. If you'd like to, you could do this, too.

Cheers,

Chris

**Comment by chrisbetz** [comment]
Hey, forget that. New release 1.2.4 is out, I've been looking at the wrong build, obviously.

**Pull request merged**
