### PR TITLE
add spark sql support

### PR DESCRIPTION
**Pull request by MarchLiu**
I use sparkling in my project. So I written those code for my jobs. Some functions with test, some without test but used in my daily jobs.

The pull request include:
- SQL context create and sql script call. Easy use as ->> form.
- DataFrame's select, select expr, where, group by, order by etc.
- GroupedData agg, min, max etc.
- UDF1, UDF2 etc, create with sparkling functions and spark java udf api.

The pull request include a json text file. It is all elements's name, description and references (not full book) from Euclid's Elements by Heath edition. Maybe it can help for someone.

### CODE REVIEW

**Comment by candland** [comment]
+1

**Comment by LukeDefeo** [comment]
We have a similar need for this functionality and we could consider improving this pr. Are the maintainers for this project considering this PR?

**Comment by LukeDefeo** [comment]
Any update on this, i am going to fork this pull request to add some more functionality, mostly parquet related. If this base PR gets merged i will create another with my changes

**Comment by chrisbetz** [comment]
Ok, will try to bring this in to the next release. Scheduling it for early february.

**Comment by chrisbetz** [comment]
tests are still green, so everything looks good ;) Thanks for this one!

**Pull request merged**
