### PR TITLE
Parquet integration

### PR DESCRIPTION
**Pull request by LukeDefeo**
Hey guys we have extended the data frame implementation with support for:
* Parquet reading writing
* clojure api for creating struct types / struct fields (schema definition for data frames)
* a few helpers for data frames

### CODE REVIEW

**Comment by BrunoBonacci** [comment]
Nice work. I've tested this PR and it works nicely.
I've used it to encode 15 billion records into parquet format via the data-frames.
Thanks @LukeDefeo.

When are you guys planning to review/merge this PR?

**Comment by BrunoBonacci** [comment]
👍

**Comment by obohrer** [comment]
👍

**Comment by johntelforduk** [comment]
👍

**Comment by chrisbetz** [comment]
Thanks for the input! I've been really busy the last month, sorry for that.

I really like your contribution! I'm merging today and will make a new version soon. I'm at Euroclojure today, so will take some days.

**Comment by chrisbetz** [comment]
Done. Released from Euroclojure: Hope you're happy to go with sparkling 2.1.0 :)

**Pull request merged**
