### PR TITLE
Correct min partition bug with coalesce-max.

### PR DESCRIPTION
**Pull request by jstokes**
- call clojure.core/min explicitly in coalesce max
- add unit tests to the core namespace for coalesce/coalesce-max

### CODE REVIEW

**Comment by jstokes** [comment]
Hey @chrisbetz, wonder if we could get this merged in. Since my team relies on the `coalesce-max` function, this bug is blocking us upgrading.

**Comment by chrisbetz** [comment]
Sorry, this totally slipped my attention! So sorry! Merged, released 1.2.5, pushed to Clojars. You're good to go. Sorry again!

**Comment by jstokes** [comment]
Thanks Chris!

**Comment by chrisbetz** [comment]
You're welcome!

**Pull request merged**
